kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  apiServerAddress: 192.168.2.151
  apiServerPort: 16443
nodes:
- role: control-plane
  image: kindest/node:v1.32.2@sha256:f226345927d7e348497136874b6d207e0b32cc52154ad8323129352923a3142f 
  # port forward 8000 on the host to 80 on this node
  extraPortMappings:
  - containerPort: 8080
    hostPort: 18080
    # optional: set the bind address on the host
    # 0.0.0.0 is the current default
    # listenAddress: "192.168.2.151"
    # optional: set the protocol to one of TCP, UDP, SCTP.
    # TCP is the default
    protocol: TCP
  # Istio ingress gateway port
  - containerPort: 30106
    hostPort: 80
  # Istio ingress gateway port
  - containerPort: 30233
    hostPort: 443
  # Ceph dashboard
  - containerPort: 30107
    hostPort: 30107
  # Kourier ingress gateway port
  - containerPort: 31080
    hostPort: 31080
    protocol: TCP
  - containerPort: 31443
    hostPort: 31443
    protocol: TCP
